### ISSUE TITLE
Adding user object in sign up functionality

### ISSUE THREAD

**Issue by valenciaaalberto** [cse110-fa22-group26/cse110-fa22-group26#44]
In the signUp.js file, the push method seems to cause an error when adding a new user to local storage (line 61). We can assign each field manually--such as db.username = userObj.username and do this for each field. However, this has to be tested in the event that multiple users sign up. An image of the description is pasted below.

![Screen Shot 2022-11-25 at 12 25 36 PM](https://user-images.githubusercontent.com/114364115/204054043-a3dc8be2-65b6-46d8-93e3-5dd0c7db777e.png)

**Comment by w3dong** [comment]
Issue has been fixed after fetching most recent js file.
