### ISSUE TITLE
homepage e2e confirmed task localStorage

### ISSUE THREAD

**Issue by ZiyanZhu1994** [cse110-fa22-group26/cse110-fa22-group26#67]
Check the task is stored into the correct location after clicking confirm button

**Comment by ZiyanZhu1994** [comment]
>  PASS  __test__/homepage.test.js
  Homepage Test
    ✓    There should be 7 Add buttons (8 ms)
    ✓  All Add button can correctly add task under all weekday list  (20 ms)
    ✓ There should be 7 input boxes that you can enter  (54 ms)
    ✓  Monday confirm button is clicked , The task is saved to the first location in localStorage  (15 ms)
    ✓  Tuesday confirm button is clicked , The task is saved to the first location in localStorage  (14 ms)
    ✓  Wednesday confirm button is clicked , The task is saved to the third location in localStorage  (20 ms)
    ✓  Thursday confirm button is clicked , The task is saved to the first location in localStorage  (13 ms)
    ✓  Friday confirm button is clicked , The task is saved to the  fifth location in localStorage  (10 ms)
    ✓  Saturday confirm button is clicked , The task is saved to the first location in localStorage  (10 ms)
    ✓  Sunday confirm button is clicked , The task is saved to the  seventh location in localStorage  (9 ms)

**Comment by RuoqianHuang** [comment]
Tests successfully checked the required functions.
