### ISSUE TITLE
homepage e2e not confirmed task localstorage 

### ISSUE THREAD

**Issue by ZiyanZhu1994** [cse110-fa22-group26/cse110-fa22-group26#68]
- Task is not saved to localStorage if the confirm button is not clicked

**Comment by ZiyanZhu1994** [comment]
>  PASS  __test__/homepage.test.js
  Homepage Test
    ✓    There should be 7 Add buttons (10 ms)
    ✓  All Add button can correctly add task under all weekday list  (21 ms)
    ✓ There should be 7 input boxes that you can enter  (56 ms)
    ✓  Monday confirm button is clicked , The task is saved to the first location in localStorage  (23 ms)
    ✓  Tuesday confirm button is not clicked , The task is not saved to the second location in localStorage  (17 ms)
    ✓  Wednesday confirm button is clicked , The task is saved to the third location in localStorage  (20 ms)
    ✓  Thursday confirm button is not clicked , The task is not saved to the fourth location in localStorage  (12 ms)
    ✓  Friday confirm button is clicked , The task is saved to the  fifth location in localStorage  (13 ms)
    ✓  Saturday confirm button is not clicked , The task is not saved to the sixth location in localStorage  (17 ms)
    ✓  Sunday confirm button is clicked , The task is saved to the  seventh location in localStorage  (15 ms)

**Comment by RuoqianHuang** [comment]
Tests successfully checked the required functions.
