### ISSUE TITLE
homepage e2e tests updates

### ISSUE THREAD

**Issue by RuoqianHuang** [cse110-fa22-group26/cse110-fa22-group26#69]
Check delete button and edit button for one day
- need to modify a little bit for testing all days (e.x. using loops)
- delete button:
      - can correctly delete certain task from localStorage
      - works also after refresh
 - edit button:
      - edit icon can open the input box

 PASS  source/__test__/homepage.test.js
  Homepage Test
    √    There should be 7 Add buttons (34 ms)
    √  All Add button can correctly add task under all weekday list  (20 ms)
    √ There should be 7 input boxes that you can enter  (47 ms)
    √  Monday confirm button is clicked , The task is saved to the first location in localStorage  (23 ms)
    √  Tuesday confirm button is not clicked , The task is not saved to the second location in localStorage  (15 ms)
    √  Wednesday confirm button is clicked , The task is saved to the third location in localStorage  (19 ms)
    √  Thursday confirm button is not clicked , The task is not saved to the fourth location in localStorage  (21 ms)
    √  Friday confirm button is clicked , The task is saved to the  fifth location in localStorage  (16 ms)
    √  Saturday confirm button is not clicked , The task is not saved to the sixth location in localStorage  (13 ms)
    √  Sunday confirm button is clicked , The task is saved to the  seventh location in localStorage  (15 ms)
    √  Monday delete button is clicked , The task is deleted from the localStorage  (9 ms)
    √  Sunday edit button is clicked , The input box is open (7 ms)
    √  Checking number of Monday tasks after reload  (88 ms)

**Comment by ZiyanZhu1994** [comment]
checked, all test cases pass

**Comment by ZiyanZhu1994** [comment]
add for loop to test all edit buttons, all confirm button block input

>  PASS  __test__/homepage.test.js
  Homepage Test
    ✓    There should be 7 Add buttons (8 ms)
    ✓  All Add button can correctly add task under all weekday list  (20 ms)
    ✓ There should be 7 input boxes that you can enter  (45 ms)
    ✓  Monday confirm button is clicked , The task is saved to the first location in localStorage  (14 ms)
    ✓  Tuesday confirm button is not clicked , The task is not saved to the second location in localStorage  (8 ms)
    ✓  Wednesday confirm button is clicked , The task is saved to the third location in localStorage  (13 ms)
    ✓  Thursday confirm button is not clicked , The task is not saved to the fourth location in localStorage  (11 ms)
    ✓  Friday confirm button is clicked , The task is saved to the  fifth location in localStorage  (11 ms)
    ✓  Saturday confirm button is not clicked , The task is not saved to the sixth location in localStorage  (9 ms)
    ✓  Sunday confirm button is clicked , The task is saved to the  seventh location in localStorage  (8 ms)
    ✓  Monday delete button is clicked , The task is deleted from the localStorage  (4 ms)
    ✓  Sunday edit button is clicked , The input box is open (4 ms)
    ✓  Checking number of Monday tasks after reload  (32 ms)
    ✓ All delete icon can correctly delete certain task from ui (54 ms)
    ✓  All delete icon can correctly delete certain task from localStorage, works also after refresh (31 ms)
    ✓  All delete clicked , works also after refresh (45 ms)
    ✓ All confirm button clicked , the input is disable (39 ms)
    ✓ All edit icon can open the input box (21 ms)

**Comment by RuoqianHuang** [comment]
Fix formatting + grammar
