### ISSUE TITLE
homepage e2e update task in localStorage

### ISSUE THREAD

**Issue by ZiyanZhu1994** [cse110-fa22-group26/cse110-fa22-group26#71]
edit the input box data and then click confirm button. Then task is updated in localStorage.
If not click nonfirm button, then task is not updated in localStorage.

**Comment by ZiyanZhu1994** [comment]
>  PASS  __test__/homepage.test.js
  Homepage Test
    ✓    There should be 7 Add buttons (7 ms)
    ✓  All Add button can correctly add task under all weekday list  (12 ms)
    ✓ There should be 7 input boxes that you can enter  (29 ms)
    ✓  Monday confirm button is clicked , The task is saved to the first location in localStorage  (7 ms)
    ✓  Tuesday confirm button is not clicked , The task is not saved to the second location in localStorage  (10 ms)
    ✓  Wednesday confirm button is clicked , The task is saved to the third location in localStorage  (8 ms)
    ✓  Thursday confirm button is not clicked , The task is not saved to the fourth location in localStorage  (7 ms)
    ✓  Friday confirm button is clicked , The task is saved to the  fifth location in localStorage  (14 ms)
    ✓  Saturday confirm button is not clicked , The task is not saved to the sixth location in localStorage  (8 ms)
    ✓  Sunday confirm button is clicked , The task is saved to the  seventh location in localStorage  (10 ms)
    ✓  Monday delete button is clicked , The task is deleted from the localStorage  (4 ms)
    ✓  Sunday edit button is clicked , The input box is open (4 ms)
    ✓  Checking number of Monday tasks after reload  (25 ms)
    ✓ All delete icon can correctly delete certain task from ui (53 ms)
    ✓  All delete icon can correctly delete certain task from localStorage, works also after refresh (24 ms)
    ✓  All delete clicked , works also after refresh (31 ms)
    ✓ All confirm button clicked , the input is disable (41 ms)
    ✓ All edit icon can open the input box (19 ms)
    ✓ The Monday confirm button is clicked - the task save in localStorage (7 ms)
    ✓  If The Monday confirm button is clicked , task is updated to in localStorage (40 ms)
    ✓  If The Monday confirm button is not clicked , task is not updated to in localStorage (5 ms)

**Comment by RuoqianHuang** [comment]
Tests successfully check functionalities.
