### ISSUE TITLE
homepage e2e checkbox

### ISSUE THREAD

**Issue by ZiyanZhu1994** [cse110-fa22-group26/cse110-fa22-group26#72]
For a task that is marked with checkbox, it still marked with checkbox after page refresh.

**Comment by ZiyanZhu1994** [comment]
>  PASS  __test__/homepage.test.js
  Homepage Test
    ✓    There should be 7 Add buttons (6 ms)
    ✓  All Add button can correctly add task under all weekday list  (10 ms)
    ✓ There should be 7 input boxes that you can enter  (27 ms)
    ✓  Monday confirm button is clicked , The task is saved to the first location in localStorage  (10 ms)
    ✓  Tuesday confirm button is not clicked , The task is not saved to the second location in localStorage  (8 ms)
    ✓  Wednesday confirm button is clicked , The task is saved to the third location in localStorage  (7 ms)
    ✓  Thursday confirm button is not clicked , The task is not saved to the fourth location in localStorage  (7 ms)
    ✓  Friday confirm button is clicked , The task is saved to the  fifth location in localStorage  (12 ms)
    ✓  Saturday confirm button is not clicked , The task is not saved to the sixth location in localStorage  (8 ms)
    ✓  Sunday confirm button is clicked , The task is saved to the  seventh location in localStorage  (9 ms)
    ✓  Monday delete button is clicked , The task is deleted from the localStorage  (3 ms)
    ✓  Sunday edit button is clicked , The input box is open (2 ms)
    ✓  Checking number of Monday tasks after reload  (27 ms)
    ✓ All delete icon can correctly delete certain task from ui (53 ms)
    ✓  All delete icon can correctly delete certain task from localStorage, works also after refresh (21 ms)
    ✓  All delete clicked , works also after refresh (34 ms)
    ✓ All confirm button clicked , the input is disable (32 ms)
    ✓ All edit icon can open the input box (18 ms)
    ✓ The Monday confirm button is clicked - the task save in localStorage (7 ms)
    ✓  If The Monday confirm button is clicked , task is updated to in localStorage (33 ms)
    ✓  If The Monday confirm button is not clicked , task is not updated to in localStorage (5 ms)
    ✓ all task  is  checked  (31 ms)
    ✓ it still marked with checkbox after page refresh  (73 ms)

**Comment by RuoqianHuang** [comment]
Tests successfully check the functionality of checkbox and checkbox after refresh.
