### ISSUE TITLE
homepage e2e collapsible test

### ISSUE THREAD

**Issue by ZiyanZhu1994** [cse110-fa22-group26/cse110-fa22-group26#82]
Test wether weekday list is collapsible

**Comment by RuoqianHuang** [comment]
Tests successfully test functionalities of homepage collapsible test:
 Homepage Test
    √ There should be 7 Add buttons (21 ms)
    √ All Add button can correctly add task under all weekday list (17 ms)
    √ There should be 7 input boxes that you can enter (59 ms)
    √ Monday confirm button is clicked, the task is saved to the first location in localStorage (22 ms)
    √ Tuesday confirm button is not clicked, the task is not saved to the second location in localStorage (23 ms)
    √ Wednesday confirm button is clicked, the task is saved to the third location in 
localStorage (24 ms)
    √ Thursday confirm button is not clicked, the task is not saved to the fourth location in localStorage (27 ms)
    √ Friday confirm button is clicked, the task is saved to the fifth location in localStorage (31 ms)
    √ Saturday confirm button is not clicked, the task is not saved to the sixth location in localStorage (46 ms)
    √ Sunday confirm button is clicked, the task is saved to the seventh location in localStorage (31 ms)
    √ Monday delete button is clicked, the task is deleted from the localStorage  (9 ms)
    √ Sunday edit button is clicked, the input box is open (7 ms)
    √ Checking number of Monday tasks after reload (121 ms)
    √ All delete icon can correctly delete certain task from ui (81 ms)
    √ All delete icon can correctly delete certain task from localStorage (53 ms)     
    √ All delete clicked, works also after refresh (289 ms)
    √ All confirm button clicked, the input box is disabled (148 ms)
    √ All edit icon can open the input box (59 ms)
    √ The Monday confirm button is clicked - the task is saved in localStorage (18 ms)
    √ If the Monday confirm button is clicked, task is updated in localStorage (13 ms)
    √ If the Monday confirm button is not clicked, task is not updated in localStorage (10 ms)
    √ all task is checked (108 ms)
    √ it still marked with checkbox after page refresh (238 ms)
    √ Test whether the collapsible of Monday can be expanded and folded (7 ms)        
    √ Test whether the collapsible of Monday can be expanded and folded (9 ms)        
    √ Test whether the collapsible of Tuesday can be expanded and folded (8 ms)
    √ Test whether the collapsible of Tuesday can be expanded and folded (12 ms)
    √ Test whether the collapsible of Sunday can be expanded and folded (11 ms)
    √ Test whether the collapsible of Sunday can be expanded and folded (15 ms)
    √ When all tasks are completed, the progress bar should be 100%  (9 ms)
    √ After all data is initialized and refreshed  (156 ms)
    √ Create four tasks per day and you should have a total of 28 tasks and all progress bars should be 0% (191 ms)
    √ With the first two tasks completed each day, all progress bars should be 50% (165 ms)
    √ When deleting the last two tasks of each day,should have a total of 14 tasks and all progress bars should be 100% (173 ms)
