### ISSUE TITLE
Homepage task count/done count e2e extra tests

### ISSUE THREAD

**Issue by RuoqianHuang** [cse110-fa22-group26/cse110-fa22-group26#85]
Add extra e2e tests for task count/done count:

results:
Homepage Test
    √ There should be 7 Add buttons (17 ms)
    √ All Add button can correctly add task under all weekday list (20 ms)
    √ There should be 7 input boxes that you can enter (50 ms)
    √ Monday confirm button is clicked, the task is saved to the first location in localStorage (15 ms)
    √ Tuesday confirm button is not clicked, the task is not saved to the second location in localStorage (15 ms)
    √ Wednesday confirm button is clicked, the task is saved to the third location in localStorage (22 ms)
    √ Thursday confirm button is not clicked, the task is not saved to the fourth location in localStorage (23 ms)
    √ Friday confirm button is clicked, the task is saved to the fifth location in localStorage (17 ms)
    √ Saturday confirm button is not clicked, the task is not saved to the sixth location in localStorage (15 ms)
    √ Sunday confirm button is clicked, the task is saved to the seventh location in localStorage (18 ms)
    √ Monday delete button is clicked, the task is deleted from the localStorage  (8 ms)
    √ Sunday edit button is clicked, the input box is open (13 ms)
    √ Checking number of Monday tasks after reload (74 ms)
    √ All delete icon can correctly delete certain task from ui (100 ms)
    √ All delete icon can correctly delete certain task from localStorage (41 ms)
    √ All delete clicked, works also after refresh (73 ms)
    √ All confirm button clicked, the input box is disabled (96 ms)
    √ All edit icon can open the input box (63 ms)
    √ The Monday confirm button is clicked - the task is saved in localStorage (18 ms)
    √ If the Monday confirm button is clicked, task is updated in localStorage (12 ms)
    √ If the Monday confirm button is not clicked, task is not updated in localStorage (8 ms)
    √ all task is checked (67 ms)
    √ it still marked with checkbox after page refresh (202 ms)
    √ Test whether the collapsible of Monday can be expanded and folded (12 ms)
    √ Test whether the collapsible of Monday can be expanded and folded (24 ms)
    √ Test whether the collapsible of Tuesday can be expanded and folded (14 ms)
    √ Test whether the collapsible of Tuesday can be expanded and folded (13 ms)
    √ Test whether the collapsible of Sunday can be expanded and folded (19 ms)
    √ Test whether the collapsible of Sunday can be expanded and folded (13 ms)
    √ When all tasks are completed, the progress bar should be 100%  (3 ms)
    √ After all data is initialized and refreshed  (107 ms)
    √ Create four tasks per day and you should have a total of 28 tasks and all progress bars should be 0% (158 ms)
    √ With the first two tasks completed each day, all progress bars should be 50% (106 ms)
    √ When deleting the last two tasks of each day,should have a total of 14 tasks and all progress bars should be 100% (162 ms)
    √ When confirmed done task is deleted, total task count & done task count went done by its amount (109 ms)
    √ When we edit and confirm existing task again, total task count & done count does not change (123 ms)
    √ When confirmed task's checkbox is unclicked, done count in weekday list title decreases by same amount (108 ms)

**Comment by ZiyanZhu1994** [comment]
Checked, all tests passed
